version: 2.1

shared: &shared-build-steps
  steps:
    - run:
        name: System information
        command: |
          env
          php -i
          composer --version
    - checkout
    - restore_cache:
        keys:
          - composer-v1-{{ checksum "composer.lock" }}
          - composer-v1-
    - run:
        name: Prepare development environment
        command: |
          mkdir -p build
          composer install --no-progress --no-interaction --prefer-dist
    - save_cache:
        key: composer-v1-{{ checksum "composer.lock" }}
        paths:
          - vendor
    - run:
        name: Test php code style
        command: |
          vendor/bin/php-cs-fixer fix --verbose --dry-run
          vendor/bin/phpcs --colors -sp src/ tests/
    - run:
        name: Run unit tests
        command: vendor/bin/phpunit --testdox --verbose
    - run:
        name: Code analysis (phpstan)
        command: vendor/bin/phpstan.phar analyse --no-progress --verbose --level max src/ tests/

jobs:
  "php-72":
    docker:
      - image: circleci/php:7.2-cli
    <<: *shared-build-steps
  "php-73":
    docker:
      - image: circleci/php:7.3-cli
    <<: *shared-build-steps

workflows:
  version: 2
  build:
    jobs:
      - "php-72"
      - "php-73"
